services:
    - docker

before_install:
    - docker --version
    - docker build -t kylemanna/openvpn .
    - docker run kylemanna/openvpn sh -c "dpkg -l openvpn openssl"

script:
    - for i in tests/*.sh; do "./$i"; done
